import type { Metadata } from "next";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import UILibraryProvider from "@/providers/UILibraryProvider";
import LayoutProvider from "@/providers/LayoutProvider";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Demo Events",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-gray-200 h-screen">
          <UILibraryProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </UILibraryProvider>
          <footer>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
